# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tesseractUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1136, 803)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter.setStyleSheet("background-color: rgb(182, 182, 182);")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.showGraphicsView = QtWidgets.QGraphicsView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showGraphicsView.sizePolicy().hasHeightForWidth())
        self.showGraphicsView.setSizePolicy(sizePolicy)
        self.showGraphicsView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.showGraphicsView.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.TextAntialiasing)
        self.showGraphicsView.setObjectName("showGraphicsView")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ocrResultTableView = QtWidgets.QTableView(self.frame)
        self.ocrResultTableView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ocrResultTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ocrResultTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ocrResultTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ocrResultTableView.setObjectName("ocrResultTableView")
        self.verticalLayout.addWidget(self.ocrResultTableView)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(240, 240, 240);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hidePushButton = QtWidgets.QPushButton(self.frame_2)
        self.hidePushButton.setObjectName("hidePushButton")
        self.horizontalLayout.addWidget(self.hidePushButton)
        self.openFilePushButton = QtWidgets.QPushButton(self.frame_2)
        self.openFilePushButton.setObjectName("openFilePushButton")
        self.horizontalLayout.addWidget(self.openFilePushButton)
        self.ocrPushButton = QtWidgets.QPushButton(self.frame_2)
        self.ocrPushButton.setObjectName("ocrPushButton")
        self.horizontalLayout.addWidget(self.ocrPushButton)
        self.screenOCRPushButton = QtWidgets.QPushButton(self.frame_2)
        self.screenOCRPushButton.setObjectName("screenOCRPushButton")
        self.horizontalLayout.addWidget(self.screenOCRPushButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1136, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "tesseract-ocr"))
        self.hidePushButton.setText(_translate("MainWindow", "隐藏边框"))
        self.openFilePushButton.setText(_translate("MainWindow", "打开图片"))
        self.ocrPushButton.setText(_translate("MainWindow", "识别-OCR"))
        self.screenOCRPushButton.setText(_translate("MainWindow", "屏幕识图"))
